app.py
from flask import Flask
from db import *
from build.setup import setup

from routes.accounts import blueprint as accounts
from routes.index import blueprint as index

app = Flask(__name__)

setup(app);

app.register_blueprint(index)
app.register_blueprint(accounts)

if __name__ == "__main__":
    app.run()

routes/accounts.py
from flask import Blueprint, redirect, session, url_for

blueprint = Blueprint('accounts', __name__, template_folder='templates')

@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    error = None
    session['logged_in'] = True
    return redirect(url_for('index'))

@blueprint.route('/logout')
def logout():
    session['logged_in'] = False
    return redirect(url_for('index'))

routes/index.py
from flask import Blueprint, redirect, session, url_for, render_template

blueprint = Blueprint('index', __name__, template_folder='templates')

@blueprint.route('/')
def index():
    context = {
        "title": "Hello World!"
        }
    return render_template('index.html', context=context)

templates/footer.html
<div id="footer">
  <a>Home</a>
  <a>About</a>
  <a>FAQ</a>
  <a>Support</a>
</div>

templates/header.html
<div id="header">
  {% if session.logged_in %}
    <a href="{{ url_for('accounts.logout') }}">Logout</a>
  {% else %}
    <a href="{{ url_for('accounts.login') }}">Login</a>
  {% endif %}
</div>

templates/index.html
{% extends "layout.html" %}
{% block body %}
  <p>Hello world!</p>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html>
<head>
  <title>{{ context.title }}</title>
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='stylesheet/style.css') }}">
  {% block head %}{% endblock %}
</head>
<body>
  {% include "header.html" %}
  <div id="body">
    {% block body %}{% endblock %}
  </div>
  {% include "footer.html" %}
</body>
</html>